### ISSUE TITLE
RethinkDB 1.13 (My Name is Nobody)

### ISSUE THREAD

**Issue by bchavez** [mfenniak/rethinkdb-net#172]
Hi there,

Just wanted a quick survey, is anyone working on 1.13 support?

Seems like there has been some significant changes in the pipeline.
- A new [JSON driver](http://rethinkdb.com/docs/driver-spec/) protocol (and soon-to-be deprecated protobuf support).
- `r.http`
- `changes()` feed

Looking at some of the issues there seems to be problems working with 1.12 with some tests failing.

Questions:
- Does the new JSON driver protocol warrant re-writing `rethinkdb-net`? Or just cretin parts? If so, which parts?

Thanks,
Brian

**Comment by cecilphillipTK** [comment]
I'm just getting started with RethinkDB, but I wanted to add my 2 cents to this post as I'm also a fan of Reactive Extensions. I've been using the python sdk thus far and I'm about to give this one a run.

Rx was one of the first things I looked for when I saw this library. I also think it makes a lot of sense in the context of change notification. It might actually help to note that you can leverage the [ToObservable<T> extension](https://msdn.microsoft.com/en-us/library/hh229584(v=vs.103).aspx) so that should be fine.

It might be beneficial to have direct Rx support, but I'd recommend have that in an optional add-on / nuget package.
