### ISSUE TITLE
Please add support for real-time push

### ISSUE THREAD

**Issue by robzhu** [mfenniak/rethinkdb-net#190]
RethinkDB 1.16 adds real-time features, as described here: http://rethinkdb.com/blog/1.16-release/

Specifically, appending .changes() to a query will cause updates to be pushed whenever that query's result would change. Any chance this functionality can be added to the driver?

**Comment by mfenniak** [comment]
The current unreleased version of the driver (in GitHub) does support the Changes command on a single target table.  The current support was added in the commit 74331f3c30ff1762468e321d8a2061ee8330beb2, where you can see it being used in a test program.

RethinkDB 1.16 looks like it adds support for a bunch of filter-based change monitoring, which sounds cool.  It probably wouldn't be hard to update the support in rethinkdb-net by changing RethinkDb.QueryTerm to operate on an ISequenceQuery rather than an ITableQuery, updating the Query factory constructor, and then writing some updated tests.  I won't be able to jump on this immediately, but, I'd happily review a pull request! :-)

**Comment by robzhu** [comment]
Thanks Mathieu, I'm not familiar enough with the code-base yet to make such a change, but I'll start looking into it.

**Comment by mfenniak** [comment]
PR #199 added support for real-time push for most of the filters and operations supported by RethinkDB 1.16.  There are a couple of filter cases that weren't added, that I've created individual issues for: #197, #198.
