### ISSUE TITLE
QueryTimeout should not apply to Changes query

### ISSUE THREAD

**Issue by kostrowski** [mfenniak/rethinkdb-net#193]
Due to its push nature, it does not make sense to timeout a `Changes` query in the same way as is done for other query types.  Presently, the timeout specified in `Connection.QueryTimeout` applies to all queries, including `Changes` queries.  It is quite reasonable to not want to timeout a `Changes` query at all, or to timeout after a different (much longer) time span than for other non-push queries.

**Comment by mfenniak** [comment]
Yup, that's a good point.

I think as a workaround, all Run methods on the connection have an overload that takes a CancellationTokenSource; if you provide a CancellationTokenSource instance, it will be used rather than the query timeout to indicate when the query should stop.  This would allow you to manually cancel the query if you wanted (by storing the token source and using CancellationTokenSource.Cancel), but it wouldn't automatically time out.

In terms of a long-term fix... hm... my first thought is that the workaround is pretty good functionally, but it's just not explicit or clear.  Perhaps we could add a "StreamChanges" method as an alternative to Run; it would never use QueryTimeout, and take a CancellationTokenSource if desired.  I think I prefer the API user being explicit about this, rather than something magical like inspecting the query and having different behavior.

**Comment by mfenniak** [comment]
Just looking at our sample program that uses .Changes; it actually demonstrates the workaround I'm suggesting of using a CancellationTokenSource.  I must have run into this when implementing Changes, but never thought of the consequences.

https://github.com/mfenniak/rethinkdb-net/blob/74331f3c30ff1762468e321d8a2061ee8330beb2/Examples/RethinkDb.Examples.ConsoleApp/Program.cs

**Comment by karlgrz** [comment]
+1 for a separate method (i.e StreamChanges) that does not time out.

**Comment by kostrowski** [comment]
Thanks for the response.  I didn't realize I could pass a `CancellationToken` in the call to `Run`, so that works perfectly well.  I had thought I'd have to write my own `AsyncEnumerableSynchronizer` in order to get that behavior.  I should learn to check the public overloads before digging into internals...

I agree that the "workaround" is actually quite good.  The only argument against it that I can think of is that a call to Run with no extra parameters should default to the most typical/expected behavior for a query, which in the case of `Changes` is to not timeout.  However, in the absence of any major refactoring to differentiate more explicitly between request/response type queries and streaming queries, thereby making a change less magical, I think it's working well as is.

Thanks again for your work on this excellent library.
