### ISSUE TITLE
How do you set durability and noreply options on Insert operations?

### ISSUE THREAD

**Issue by cecilphillip** [mfenniak/rethinkdb-net#221]
I'm going through a reference where these settings are used. I see there's suppose for setting conflict, but not these other two. How do you set these?

**Comment by mfenniak** [comment]
Hi Cecil,

I'm sorry to say that neither option is currently supported by the driver.  The durability option would probably be fairly straight-forward to implement, but I think the noreply option would require some new method signatures since it varies the results of a query (obviously).  I'm afraid I won't be able to jump on implementing this right now, but I'd be able to review a pull request if you (or another contributor) are interested in submitting one.

**Comment by cecilphillip** [comment]
Ok, Thanks Mathieu
